version: "3.8"
services:
    app:
        image: testdocker4web-php:latest
        # build:
        #     context: .
        #     dockerfile: Dockerfile
        container_name: fkip_web_app
        # restart: unless-stopped
        # working_dir: /var/www/html
        volumes:
            - ../../.env:/var/www/html/.env
        ports:
            - "8080:8080"
            - "9010:9000"
        networks:
            fkip_web:
            rabbitmq_shared_network:
            minio_minionetwork:

    nginx:
        image: testdocker4web-nginx:latest
        container_name: fkip_web_nginx
        restart: unless-stopped
        ports:
            - "8007:80"
        volumes:
            - ../../public:/var/www/html/public
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - fkip_web
        depends_on:
            - app

    db:
        image: mysql:8.0
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u",
                    "root",
                    "-p${MYSQL_ROOT_PASSWORD}",
                ]
            interval: 5s
            timeout: 5s
            retries: 5
        container_name: fkip_web_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: password
            MYSQL_USER: laravel
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - fkip_web

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: fkip_web_phpmyadmin
        environment:
            PMA_PORT: 3306
            PMA_HOST: fkip_web_db
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "8082:80"
        networks:
            - fkip_web
        depends_on:
            - db

networks:
    fkip_web:
        driver: bridge
        ipam:
            config:
                - subnet: 172.28.0.0/16
    rabbitmq_shared_network:
        external: true
        name: rabbitmq_shared_network
    minio_minionetwork: # Tambahkan ini
        external: true

volumes:
    dbdata:
        driver: local
