version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: fkip_web_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ../../:/var/www/html
        networks:
            fkip_web:
                ipv4_address: 172.28.0.10
        ports:
            - "8080:9000"

    nginx:
        image: nginx:alpine
        container_name: fkip_web_nginx
        restart: unless-stopped
        ports:
            - "8007:80"
        volumes:
            - ../../:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - fkip_web

    db:
        image: mysql:8.0
        container_name: fkip_web_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: password
            MYSQL_USER: laravel
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - fkip_web

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: fkip_web_phpmyadmin
        environment:
            PMA_PORT: 3306
            PMA_HOST: fkip_web_db
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "8082:80"
        networks:
            - fkip_web
        depends_on:
            - db

networks:
    fkip_web:
        driver: bridge
        ipam:
            config:
                - subnet: 172.28.0.0/16 # Definisikan subnet untuk IP static

volumes:
    dbdata:
        driver: local
