services:
  app:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
      target: php
      tags:
        - "fkip_web:latest"
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
      target: nginx
      tags:
        - "fkip_nginx:latest"
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
