services:
  app:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    image: "ghcr.io/ardiman-xyz/fkip_web:latest"

  nginx:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    image: "ghcr.io/ardiman-xyz/fkip_web-nginx:latest"
