name: Deploy Staging
on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write
  actions: write # Tambahkan ini
  id-token: write # Dan ini

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Application Image
        run: |
          docker build -f docker/prod/prod.Dockerfile -t ghcr.io/ardiman-xyz/fkip_web_app:latest .
          docker push ghcr.io/ardiman-xyz/fkip_web_app:latest

      - name: Extract Assets and Public Files
        run: |
          docker create --name temp_app ghcr.io/ardiman-xyz/fkip_web_app:latest
          docker cp temp_app:/var/www/html/public ./public_files
          docker rm temp_app

      - name: Build Nginx Image
        run: |
          docker build \
            --build-arg PUBLIC_FILES=./public_files \
            -f docker/prod/nginx/prod.Dockerfile \
            -t ghcr.io/ardiman-xyz/fkip_web_nginx:latest .
          docker push ghcr.io/ardiman-xyz/fkip_web_nginx:latest
