name: Deploy Staging
on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write
  actions: write # Tambahkan ini
  id-token: write # Dan ini

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push images
        run: |
          docker compose -f docker-compose.staging.yml build
          docker tag ghcr.io/ardiman-xyz/fkip_web:latest ghcr.io/ardiman-xyz/fkip_web:staging
          docker tag ghcr.io/ardiman-xyz/fkip_web-nginx:latest ghcr.io/ardiman-xyz/fkip_web-nginx:staging
          docker push ghcr.io/ardiman-xyz/fkip_web:staging
          docker push ghcr.io/ardiman-xyz/fkip_web-nginx:staging

      # - name: Deploy to staging
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.STAGING_HOST }}
      #     username: ${{ secrets.STAGING_USER }}
      #     key: ${{ secrets.STAGING_SSH_KEY }}
      #     script: |
      #       cd /var/www/html/docker/ods-fkip
      #       docker compose pull
      #       docker compose down
      #       docker compose up -d
